### ISSUE TITLE
IoTAPIPortingTool: "All dll's are compatible" but how can I run Win32 app?

### ISSUE THREAD

**Issue by AlexandrSurkov** [ms-iot/iot-utilities#20]
Hello!
I am trying to use IoTAPIPortingTool on my Win32 WinForms app and it says 
"All DLL's are compatible
Number of functions incompatible: 1"
This incompatible function is:
_CorDllMain from mscoree.dll

What does it means? How can I run (even with some modifications) my app on Windows IoT Core?
I can't even compile my code for UWP app in Visual Studio because it can't find many namespaces and classes. For example System.Net.Sockets.Socket or System.Threading.Thread. But IoTAPIPortingTool  says "all right".

**Comment by IoTGirl** [comment]
https://developer.microsoft.com/en-us/windows/iot/win10/tools/iotapiportingtool says the tool will suggest alternative UWP APIs to replace the Win32 calls.

You can also take a look at this discussion thread on MSDN https://social.msdn.microsoft.com/Forums/en-US/5655a3a2-c7ae-4ee1-8d60-08cec062c3ec/windows-10-iot-core-api-porting-tool-how-to-interpret-the-results?forum=WindowsIoT

**Comment by AlexandrSurkov** [comment]
Thanks for reply!
Is I understand right that I can't run Win32 app at Windows 10IoT Core? Is Porting tool helps to change Win32 calls to UWP calls to convert Win32App to UWP app?

**Comment by IoTGirl** [comment]
Closing as stale - IoT Core porting tool docs answer the final question [https://developer.microsoft.com/en-us/windows/iot/docs/iotcoreportingtool](https://developer.microsoft.com/en-us/windows/iot/docs/iotcoreportingtool) 

> Windows 10 IoT Core only supports a subset of the Win32 and .Net API surface area available on various prior versions of Windows. This tool will scan your binaries and give you a report of the APIs these binaries use that aren’t available and give suggestions for possible replacements
