### ISSUE TITLE
HDMI CEC / Win32API, Turn on/off monitor or TV

### ISSUE THREAD

**Issue by iqmeta** [ms-iot/iot-utilities#25]
Hi,
is it somehow possible to use the converter to get kind of API access of turn on / off monitor from a UWA?

https://social.msdn.microsoft.com/Forums/sqlserver/de-DE/32ce3029-c1e6-4f27-b0bd-f19041338820/how-to-use-cec-from-windows-10-iot?forum=WindowsIoT

https://github.com/Pulse-Eight/libcec/issues/130

Cheers.

**Comment by Narnain** [comment]
Is there any update on this?

**Comment by IoTGirl** [comment]
Hi @iqmeta and @Narnain,
There is no direct API access in Windows to turn off the display. Rather like your desktop/laptop this is controlled by a power aware driver in combination with system settings in the OS.
However, you could certainly build a custom driver that allowed an application the ability to turn the screen off but that would bot be built in to windows.
Sincerely,
IoTGirl
