### ISSUE TITLE
invalid SQL for SQLLite in program.cs

### ISSUE THREAD

**Issue by fgenolini** [ms-iot/iot-utilities#26]
[Edit: pull request added]
program.cs in lines 24 and 25 generate invalid SQL syntax:

`
        private const string functionSelect = "SELECT * FROM FUNCTION WHERE F_NAME = '{0}';";
        private const string functionSelectWithDll = functionSelect + "AND F_DLL_NAME = '{1}';";
`

line 24 must not have a semi-colon, and therefore the code should be instead:

`
        private const string functionSelect = "SELECT * FROM FUNCTION WHERE F_NAME = '{0}'";
        private const string functionSelectWithDll = functionSelect + " AND F_DLL_NAME = '{1}';";
`

**Comment by IoTGirl** [comment]
Closing: [https://github.com/ms-iot/iot-utilities/pull/27](https://github.com/ms-iot/iot-utilities/pull/27) was merged
