### ISSUE TITLE
Many valid Win32 APIs are listed as incompatible, but they are not

### ISSUE THREAD

**Issue by fgenolini** [ms-iot/iot-utilities#28]
Many essential low level Win32 API calls are reported as incompatible with Win 10 IoT Core by this tool, but they should instead be correctly found to be recognised and supported by the operating system (Win 10 IoT Core on Raspberry Pi 2B in my case).

Try a very simple C++ Win32 application that only prints out values returned by GetCurrentProcessId or GetCurrentThreadId, compile in Visual Studio 2015 for ARM, deploy to Raspberry Pi 2, run using ssh (PUTTY), and you will see that the command line application runs and returns valid values.
Yet the IOT API Porting Tool - Scan results list both functions as not compatible (misspelt in the tool as comptible).

The problem comes from the file IoTDLLs.txt, which is very incomplete.
I have manually edited this file (my additions are in the file [Extra-IoTDLLs.txt](https://github.com/ms-iot/iot-utilities/files/474743/Extra-IoTDLLs.txt)) in Visual Studio 2015 and redeployed it, and then called the tool with the generate option again.  Now the tool correctly recognises low level C Win32 APIs that I know for certain are present and working on Windows 10 IoT Core for ARM (Raspberry Pi 2).  This is a lot of work however, to test every single low level Win32 API call.  Surely this should be documented somewhere in the Microsoft web site and included in this app?

**Comment by IoTGirl** [comment]
Hi Ale, Brian & Lou,
Can you please review?
Sincerest thanks,
IoTGirl

**Comment by IoTGirl** [comment]
Hi @fgenolini.

The code and docs are public. Would you like to submit a pull changelist?

Sincerely,
IoTGirl

**Comment by fgenolini** [comment]
Hi,

I might have missed an important point, so I welcome any comment on my first proposal (see attached file Extra-IoTDLLs.txt).

It could very well be that all the expected legacy Win32 C API are still there in these early versions of Win10 IoT but that the IoT team intends to obsolete them / remove them.

For the moment I am glad that Win10 IoT exists and that all my old code and experience still work.  However I am open to new learning and I would actually rather have a modern C++ (ISO C++ 17) or C# (native) API than the old C API.

Regards,

**Comment by saraclay** [comment]
Hello - since recent updates may have fixed your issue, I will close this for now. If you'd like to address an issue, please file it at: www.github.com/MicrosoftDocs/windows-iotcore-docs
