### ISSUE TITLE
WindowsIoTCoreWatcher is not listing any devices after Windows 10 IoT Core update

### ISSUE THREAD

**Issue by cristianst85** [ms-iot/iot-utilities#31]
After updating Windows 10 IoT Core to the latest version (10.0.14393.187) my device (Raspberry Pi 2) is now sending UDP packets with the length of 446 bytes.

A sample packet can be download from [here](http://disruptivesoftware.ro/temp/Win10IoTCore-UDP-Packet-446bytes.zip) (the MAC address was eddited to ff:ff:ff:ff:ff:ff).

**Comment by IoTGirl** [comment]
Closing - IoTCoreWatcher was replaced by IoT Core Dashboard. Please attempt with IoTCoreDashboard and give feedback using the feedback application for Windows 10.
